#!/bin/bash
# Build the phone-format tutorial video for Copy Markers.
#
# Not a screen recording — a designed sequence: slides in the steelblue look,
# Ken-Burns zooms, crossfades, and our own synthetic 128 BPM beat underneath
# (generated by tests/gen_demo.lua, so there is no licence to clear).
#
# Output: copy-markers-tutorial.mp4, 1080x1920 (9:16), ~30 s, H.264 + AAC.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG="$(cd "$HERE/../.." && pwd)"
IMG="$PKG/Tutorials/img"
BEAT="$PKG/Demo Project/steelblue_demo_beat.wav"
CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
WORK="$HERE/work"
OUT="$HERE/copy-markers-tutorial.mp4"

FPS=30
FADE=0.5

mkdir -p "$WORK"

# --- tight crops for the phone screen ----------------------------------------

ffmpeg -y -loglevel error -i "$IMG/copy-01-selection.png" -vf "crop=1250:430:20:900"  "$WORK/v-manager-select.png"
ffmpeg -y -loglevel error -i "$IMG/copy-02-result.png"    -vf "crop=1160:560:380:1055"  "$WORK/v-manager-result.png"

# --- the brand mark, knocked out for a dark background ------------------------

sed 's/#FFFFFF/#26262B/' "$PKG/Tutorials/mark.svg" > "$WORK/mark-dark.svg"

# --- slides -------------------------------------------------------------------
# CSS pixels are laid out at 1080x1920; Chrome renders at scale factor 2, so the
# PNGs are 2160x3840 — zoompan then has headroom and does not shimmer.

slide() {
  local name="$1" body="$2"
  cat > "$WORK/$name.html" <<HTML
<!doctype html><html><head><meta charset="utf-8"><style>
  * { margin:0; box-sizing:border-box; }
  body {
    width:1080px; height:1920px; overflow:hidden;
    background:#1B1B1E; color:#E8E8EA;
    font:400 44px/1.45 -apple-system, "Helvetica Neue", sans-serif;
    display:flex; flex-direction:column; justify-content:center;
    padding:90px 84px; position:relative;
  }
  .rule { position:absolute; left:0; right:0; top:0; height:14px; background:#4682B4; }
  .brand { position:absolute; top:64px; left:84px; display:flex; gap:22px; align-items:center; }
  .brand img { width:74px; }
  .brand div b { display:block; font-size:40px; font-weight:600; letter-spacing:-0.01em; }
  .brand div span { display:block; font-size:19px; letter-spacing:.24em; color:#8A8A92; }
  .step {
    width:96px; height:96px; border-radius:50%; background:#4682B4; color:#fff;
    font-size:52px; font-weight:700; display:flex; align-items:center; justify-content:center;
    margin-bottom:44px;
  }
  h1 { font-size:104px; line-height:1.08; font-weight:700; letter-spacing:-0.02em; margin-bottom:36px; }
  h2 { font-size:74px; line-height:1.15; font-weight:700; letter-spacing:-0.015em; margin-bottom:30px; }
  p  { font-size:46px; color:#B9B9BF; max-width:850px; }
  p strong { color:#E8E8EA; font-weight:600; }
  .shot { margin-top:70px; border-radius:18px; overflow:hidden; border:2px solid #3C3C40;
          box-shadow:0 40px 90px rgba(0,0,0,.55); }
  .shot img { width:100%; display:block; }
  .accent { color:#7FB2DC; }
  .warnbar { width:96px; height:96px; border-radius:50%; background:#E0A030; color:#1B1B1E;
             font-size:60px; font-weight:800; display:flex; align-items:center; justify-content:center;
             margin-bottom:44px; }
  .foot { position:absolute; bottom:70px; left:84px; right:84px; font-size:30px; color:#6E6E76; }
</style></head><body>
<div class="rule"></div>
<div class="brand"><img src="mark-dark.svg"><div><b>steelblue</b><span>STUDIOS</span></div></div>
$body
<div class="foot">steelblue LD Plugin Set — Copy Markers</div>
</body></html>
HTML
  "$CHROME" --headless --disable-gpu --no-sandbox --hide-scrollbars \
    --force-device-scale-factor=2 --window-size=1080,1920 \
    --screenshot="$WORK/$name.png" "file://$WORK/$name.html" 2>/dev/null
}

slide s1 '
  <h1>Copy<br>Markers</h1>
  <p>Duplicate a whole block of cues — <strong>spacing, names and colours kept.</strong></p>'

slide s2 '
  <h2>The chorus cues<br>return later<br>in the song?</h2>
  <p><strong>Don&rsquo;t rebuild them.</strong> Copy the block once and drop it wherever it plays again.</p>'

slide s3 '
  <div class="step">1</div>
  <h2>Select the markers</h2>
  <p>in the <strong>Region/Marker Manager</strong> — shift-click for a range.</p>
  <div class="shot"><img src="v-manager-select.png"></div>'

slide s4 '
  <div class="warnbar">!</div>
  <h2>Click into the<br>arrange first</h2>
  <p>While the manager has keyboard focus it <strong>swallows the shortcut</strong> — and clears your selection. One click in the arrange fixes it.</p>'

slide s5 '
  <div class="step">2</div>
  <h2>Run Copy Markers</h2>
  <p>with the shortcut you assigned. It reads your selection <span class="accent">live</span>.</p>
  <div class="shot" style="max-width:760px"><img src="../../img/copy-01a-window.png"></div>'

slide s6 '
  <div class="step">3</div>
  <h2>Copy to cursor</h2>
  <p>or type a bar or timecode position. <strong>Green means done.</strong></p>
  <div class="shot" style="max-width:760px"><img src="../../img/copy-02a-window.png"></div>'

slide s7 '
  <h2>The block arrives<br>as a block</h2>
  <p>Two bars apart in the original — <strong>two bars apart in the copy.</strong></p>
  <div class="shot"><img src="v-manager-result.png"></div>'

slide s8 '
  <h1 style="font-size:88px">Four tools for<br>cue programming</h1>
  <p>Live BPM Analyzer &middot; MIDI notes to markers &middot; Rename markers &middot; Copy Markers</p>
  <p style="margin-top:28px; font-size:38px; color:#8A8A92">Full guides in the package.</p>'

# --- one clip per slide, alternating zoom in / zoom out ------------------------

DUR=(3.0 3.5 4.5 4.0 4.5 4.5 4.5 3.5)

for i in 1 2 3 4 5 6 7 8; do
  d="${DUR[$((i-1))]}"
  frames=$(awk "BEGIN{printf \"%d\", $d*$FPS}")
  if [ $((i % 2)) -eq 1 ]; then
    z="min(1+0.07*on/$frames,1.07)"                 # slow push in
  else
    z="max(1.07-0.07*on/$frames,1.0)"               # slow pull out
  fi
  ffmpeg -y -loglevel error -loop 1 -framerate $FPS -i "$WORK/s$i.png" \
    -vf "zoompan=z='$z':d=$frames:x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':s=1080x1920:fps=$FPS" \
    -frames:v "$frames" -pix_fmt yuv420p "$WORK/c$i.mp4"
done

# --- crossfade chain -----------------------------------------------------------

OFFSETS=$(awk -v fade=$FADE 'BEGIN{
  split("3.0 3.5 4.5 4.0 4.5 4.5 4.5 3.5", d, " ");
  o = 0
  for (i = 1; i <= 7; i++) { o += d[i] - fade; printf "%s%.2f", (i>1?" ":""), o }
}')
read -r O1 O2 O3 O4 O5 O6 O7 <<< "$OFFSETS"
TOTAL=$(awk -v fade=$FADE 'BEGIN{ split("3.0 3.5 4.5 4.0 4.5 4.5 4.5 3.5", d, " ");
  t=0; for(i=1;i<=8;i++) t+=d[i]; t-=7*fade; printf "%.2f", t }')

ffmpeg -y -loglevel error \
  -i "$WORK/c1.mp4" -i "$WORK/c2.mp4" -i "$WORK/c3.mp4" -i "$WORK/c4.mp4" \
  -i "$WORK/c5.mp4" -i "$WORK/c6.mp4" -i "$WORK/c7.mp4" -i "$WORK/c8.mp4" \
  -stream_loop -1 -i "$BEAT" \
  -filter_complex "
    [0][1]xfade=transition=fade:duration=$FADE:offset=$O1[v1];
    [v1][2]xfade=transition=fade:duration=$FADE:offset=$O2[v2];
    [v2][3]xfade=transition=fade:duration=$FADE:offset=$O3[v3];
    [v3][4]xfade=transition=fade:duration=$FADE:offset=$O4[v4];
    [v4][5]xfade=transition=fade:duration=$FADE:offset=$O5[v5];
    [v5][6]xfade=transition=fade:duration=$FADE:offset=$O6[v6];
    [v6][7]xfade=transition=fade:duration=$FADE:offset=$O7[video];
    [8:a]atrim=0:$TOTAL,volume=0.22,afade=t=in:d=1.2,afade=t=out:st=$(awk "BEGIN{print $TOTAL-2.5}"):d=2.5[audio]
  " \
  -map "[video]" -map "[audio]" \
  -c:v libx264 -crf 20 -preset medium -pix_fmt yuv420p -r $FPS \
  -c:a aac -b:a 128k -movflags +faststart \
  -t "$TOTAL" "$OUT"

echo "built: $OUT"
echo "  $(du -h "$OUT" | cut -f1), ${TOTAL}s, 1080x1920 @ ${FPS}fps"
